name: Exercice 1 - Valider un projet

on:
  push:      

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Install nodejs
        uses: actions/setup-node@v7
        with:
          node-version: 24.21.0

      - name: Put dependances in cache
        uses: actions/cache@v5
        with: 
          path: ~/.npm
          key: npm-${{runner-os}}-${{ hashFiles('package-lock.json') }}

      - name: install dependances
        run: npm ci # equivalent de npm install mais mieux car sur d'avoir toujours les meme versions prises dans le package.lock
      
      #- name: Run tests
      #  run: npm run test
      
      - if: always()
        name: Job Status
        run: |
          echo "Status: ${{job.status}}" >> $GITHUB_STEP_SUMMARY
          echo "Commit ID: ${{github.sha}}" >> $GITHUB_STEP_SUMMARY

    