name: Exercice 3 - Envs et Parallélislùe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v7

      - name: Setup nodejs
        uses: actions/setup-node@v7
        with:
          node-version: 24.21.0

      - name: Put dependances in cache
        uses: actions/cache@v5
        with: 
          path: ~/.npm
          key: npm -${{ hashFiles('package-lock.json') }}

      - name: install dependances
        run: npm ci

      - name: run build
        run: npm run build

      - name: check if build exists
        run: |
          if [ ! -d dist]; then
            echo "::error:: Le dossier dist/ n'existe pas"
            exit 1
          fi

      - name: Create artefact
        uses: actions/upload-artifact@v7
        with:
          name: application
          path: dist/
      
      
  
  test:
    needs: build

    strategy:
      fail-fast: false
      max-parallel: 2
    
      matrix:
        node: [20, 22]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix:.os}}

    steps:
      - name: get artefact
        uses: actions/upload-artifact@v7
        with:
          name: application
          path: dist/

      - name: Run tests
        run: npm run test

      - if: always()
        name: Job Status
        run: |
          echo "Status: ${{job.status}}" >> $GITHUB_STEP_SUMMARY
          echo "Commit ID: ${{github.sha}}" >> $GITHUB_STEP_SUMMARY
    